parameters: 
  - name: servicePrincipal
    type: string
  - name: environment
    type: string

jobs: 
  - job: ValidateAndDeploy
    displayName: "Validate and Deploy Bundle"
    ${{ if eq(parameters.environment, 'dev') }}:
      dependsOn: 
        - SecurityChecks
        - Lint
    ${{ if eq(parameters.environment, 'tst') }}:
      pool: 
        name: 'vmss-shared'
    variables:
      - template: ../../variables.yml
        parameters:
          environment: ${{ parameters.environment }}
    
    steps:
      # 1. Install Agent Requirements & Allowing Executables
      - script: |   
          # Exit immediately if any command fails
          set -e

          # Install the Databricks CLI
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          
          # Install build
          pip install build

          # Enable all scripts to be executable within scripts folder
          chmod +x ./cicd_templates/scripts/*
        displayName: "Install Agent Requirements & Allowing Executables"

      # 2. Get and Increment Semantic Version Tag
      - script: ./cicd_templates/scripts/bump-version.sh
        name: setTag
        displayName: "Get and Increment Tag"
      
      # 3. Generate Environment Variables
      - script: |
          # Exit immediately if any command fails
          set -e    
          
          # Generate all required variables      
          export WHL_FILE=cdp_core-$(setTag.BUILD_VERSION)-py3-none-any.whl
          export BUNDLE_VAR="whl_path=/Workspace/Users/$(SPN_ID)/.bundle/cdp_core/artifacts/.internal/${WHL_FILE},spn_id=$(SPN_ID),policy_id=$(POLICY_ID),data_engineering_group=$(DATA_ENGINEERING_GROUP),warehouse_id=$(WAREHOUSE_ID),catalog=$(CATALOG)"

          # Persist variables 
          echo "##vso[task.setvariable variable=BUNDLE_VAR;isOutput=true]$BUNDLE_VAR";
        name: setEnvVars
        displayName: "Setting Environment Variables"

      # 6. Validate Databricks Bundle
      - template: ../databricks_azure_cli.yml
        parameters:
          servicePrincipal: ${{ parameters.servicePrincipal }}
          description: "Validating Databricks Bundle"
          inlineScript: |
            databricks bundle validate -t ${{ parameters.environment }} --var=$(setEnvVars.BUNDLE_VAR)

      # 7. Deploy Databricks Bundle
      - template: ../databricks_azure_cli.yml
        parameters:
          servicePrincipal: ${{ parameters.servicePrincipal }}
          description: "Deploy Databricks Bundle"
          inlineScript: |
            export BUILD_VERSION=$(setTag.BUILD_VERSION)
            databricks bundle deploy -t ${{ parameters.environment }} --var=$(setEnvVars.BUNDLE_VAR)
