trigger:
  branches:
    exclude:
      - "*" # don't trigger on any branch commits
  tags:
    include:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"

pr:
  branches:
    exclude:
      - "*" # don't trigger on PRs either

variables:
  - group: cdp-core-pipeline-global-vars

stages:
  ############################## PROD Stage ########################################
  - stage: Verify
    displayName: "Verify Commit on Main"
    jobs:
      - job: VerifyCommit
        displayName: "Verify commit belongs to main"
        steps:
          - checkout: self
          - bash: |
              COMMIT_SHA=$(Build.SourceVersion)
              echo "Checking if the tag's commit ($COMMIT_SHA) is part of main..."
              if git branch -r --contains $COMMIT_SHA | grep -q "origin/main"; then
                echo "✅ The tagged commit is on main."
              else
                echo "❌ The tagged commit is NOT on main. Skipping deployment."
                echo "##vso[task.complete result=SucceededWithIssues;]Tag commit not on main"
                exit 0
              fi
            displayName: "Check tag's commit ancestry"

  - stage: PROD
    displayName: "PROD Deployment"
    dependsOn: Verify
    condition: succeeded()
    jobs:
      - template: templates/prod.yml
