trigger:
  branches:
    include:
      - main

pr:
  branches:
    exclude:
      - "*"

parameters:
  - name: releaseNotes
    displayName: 'Release Notes'
    type: string
    default: 'Release notes for the production deployment.'
  - name: notifyUsers
    displayName: 'Notify Users - one email per line'
    type: object
    default: []

variables:
  - group: cdp-core-pipeline-global-vars 

stages:
  ############################## TEST Stage ########################################
  - template: templates/test.yml

  ############################## APPROVAL Gate #####################################
  - stage: ReleaseApproval
    condition: succeeded('TEST')
    displayName: "RELEASE APPROVAL GATE"
    jobs:
      - template: templates/modules/jobs/approval_gate.yml
        parameters:
          notifyUsers: ${{ parameters.notifyUsers }}

  ############################## RELEASE Stage #####################################
  - stage: TagAndRelease
    displayName: "TAG & RELEASE"
    condition: succeeded('PROD') 
    jobs:
      - template: templates/modules/jobs/tag_and_release.yml
