trigger:
  branches:
    include:
      - main

stages:
  - stage: Dev
    displayName: "DEV"
    jobs:
      - job: DevJob1
        displayName: "Install Databricks CLI"
        steps:
          - script: |
              winget search databricks
              winget install Databricks.DatabricksCLI
              databricks -v
            displayName: "Install Databricks CLI"


  
  - stage: Test
    displayName: "TEST"
    jobs:
      - job: DevJob2
        displayName: "Dev Job 2"
        steps:
          - script: echo "Hello from Dev Job 2"