trigger:
  branches:
    include:
      - main

stages:
  - stage: Dev
    displayName: "DEV"
    jobs:
      - job: DevJob1
        displayName: "Install Databricks CLI"
        steps:
          - script: |
              pip install databricks-cli
            displayName: "Install Databricks CLI"

          - script: echo "Hello World from Dev Job 1"
            displayName: "Print Hello World"

      - job: DevJob2
        displayName: "Dev Job 2"
        steps:
          - script: echo "Hello from Dev Job 2"