trigger:
  branches:
    include:
      - main          # only consider tags created from main
  tags:
    include:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

pr:
  branches:
    exclude:
      - "*"

variables:
  - group: cdp-core-pipeline-global-vars 

stages:
  ############################## PROD Stage ########################################
  - template: templates/prod.yml
  

