trigger:
  branches:
    include:
      - main

stages:
  - stage: Dev
    displayName: "DEV"
    jobs:
      - job: DevJob1
        displayName: "Install Databricks CLI"
        steps:
          - script: |
              brew tap databricks/tap
              brew install databricks
            displayName: "Install Databricks CLI"

          - script: |
              databricks -v
            displayName: "est"
  
  - stage: Test
    displayName: "TEST"
    jobs:
      - job: DevJob2
        displayName: "Dev Job 2"
        steps:
          - script: echo "Hello from Dev Job 2"