parameters: 
  - name: servicePrincipal
    type: string

jobs: 
  - job: UnitTests
    displayName: "Unit Tests"
    dependsOn: 
      - ValidateAndDeploy
    variables:
      - name: BUNDLE_VAR
        value: $[ dependencies.ValidateAndDeploy.outputs['setEnvVars.BUNDLE_VAR'] ]
    steps:
      # 1. Install Databricks CLI
      - script: |   
          # Exit immediately if any command fails
          set -e

          # Install the Databricks CLI
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        displayName: "Install Agent Requirements"
      
      # 2. Run Unit Tests
      - template: ../databricks_azure_cli.yml
        parameters:
          servicePrincipal: ${{ parameters.servicePrincipal }}
          description: "Unit Tests"
          inlineScript: |
            databricks bundle run jb_pytest --var=$(BUNDLE_VAR)