parameters:
  - name: environment
    type: string

stages:
  - stage: DEV
    displayName: "DEV"
    jobs:
      - job: DEV
        displayName: "Deploy DEV"
        variables:
          - template: variables.yml
            parameters:
              environment: ${{ parameters.environment }}

        steps:
          # 1. Install All Requirements
          - script: |
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
              pip install uv pylint yamllint
            displayName: "Install Agent Requirements"

          # 2. Set Environment Variables
          - script: |
              set -e
              export DATABRICKS_HOST=$(DATABRICKS_HOST)
              export ENVIRONMENT=$(ENVIRONMENT)
            displayName: "Setting Environment Variables"

          # 3. Run PyLint
          # - script: |
          #     pylint src/ --rcfile=.pylintrc --exit-zero
          #   displayName: "Run PyLint"
          
          # 4. Run YamlLint
          # - script: |
          #     yamllint -c .yamllint . || true
          #   displayName: "Run YamlLint"

          # 5. Validate Databricks Bundle
          # - template: steps/dev_azure_cli.yml
          #   parameters:
          #     description: "Validating Databricks Bundle"
          #     inlineScript: |
          #       databricks bundle validate --var="environment=$(ENVIRONMENT)"

          # 6. Deploy Databricks Bundle
          # - template: steps/dev_azure_cli.yml
          #   parameters:
          #     description: "Deploy Databricks Bundle"
          #     inlineScript: |
          #       databricks bundle deploy --var="environment=$(ENVIRONMENT)"     
          
          # 7. Run Unit Tests
          # - template: steps/dev_azure_cli.yml
          #   parameters:
          #     description: "Unit Tests"
          #     inlineScript: |
          #       databricks bundle run jb_pytest --var="environment=$(ENVIRONMENT)"
          
          # 8. Copy whl file to shared area
          - template: steps/dev_azure_cli.yml
            parameters:
              description: "Copying whl file to shared area"
              inlineScript: |    
                echo $(SPN_ID)
                echo $(ENVIRONMENT)
                echo $pwd
                echo pwd
                echo $dir   
                echo dir
                databricks fs ls ..
                # databricks fs cp /Workspace/Users/$(SPN_ID)/.bundle/cdp_core/$(ENVIRONMENT)/artifacts/.internal/cdp_core-0.2.7-py3-none-any.whl /Shared/artifacts/
                databricks fs cp /Workspace/Users/6f4aedc5-6ff3-48f3-8d6a-e4c03148e42f/.bundle/cdp_core/development/artifacts/.internal/cdp_core-0.2.7-py3-none-any.whl /Shared/artifacts/