stages:
  - stage: DEV
    displayName: "DEV"
    jobs:
      - job: DEV
        displayName: "Deploy DEV"
        steps:
          - script: |
              echo "Installing Requirements"
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
              pip install uv pylint yamllint
            displayName: "Install Agent Requirements"

          - script: |
              echo "Running Pylint"
              pylint src/ --rcfile=.pylintrc --exit-zero
            displayName: "Run PyLint"
      
          - script: |
              echo "Running Yaml Lint"
              yamllint -c .yamllint . || true
            displayName: "Run YamlLint"

          - task: CopyFiles@2
            displayName: "Get Artifacts"
            inputs:
              SourceFolder: '$(Build.Repository.LocalPath)'
              Contents: '**'
              TargetFolder: '$(Build.BinariesDirectory)'
              CleanTargetFolder: true
              OverWrite: true

          - task: replacetoken@5
            inputs:
              rootDirectory: '$(Build.BinariesDirectory)/'
              targetFiles: '**/databricks.yml'
              tokenPattern: 'azpipelines'
              writeBOM: true
              encoding: 'auto'
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
            displayName: "Replace Variable Values in Databricks YML"

          - task: AzureCLI@2
            condition: succeeded()
            displayName: "Validate Databricks Bundle"
            inputs:
              azureSubscription: $(SPN_ID)
              useGlobalConfig: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                export DATABRICKS_HOST=$(DATABRICKS_DEV_HOST)
                echo "Validating Databricks Bundle"
                databricks bundle validate
          
          - task: AzureCLI@2
            condition: succeeded()
            displayName: "Deploy Databricks Bundle"
            inputs:
              azureSubscription: $(SPN_ID)
              useGlobalConfig: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                echo "Deploying Databricks Bundle"
                databricks bundle deploy --target dev
          
          - task: AzureCLI@2
            condition: succeeded()
            displayName: "Unit Tests"
            inputs:
              azureSubscription: $(SPN_ID)
              useGlobalConfig: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                databricks jobs submit --json @unit_test.json --no-wait