parameters:
  - name: environment
    type: string

stages:
  - stage: DEV
    displayName: "DEV"
    jobs:
      - job: DEV
        displayName: "Deploy DEV"
        variables:
          - template: variables.yml
            parameters:
              environment: ${{ parameters.environment }}

        steps:
          # 1. Install All Requirements
          - script: |
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
              pip install pylint yamllint
            displayName: "Install Agent Requirements"
          
          # 2. Get and Increment Tag
          - script: templates/scripts/bump-version.sh
            name: setTag
            displayName: "Get and Increment Tag"

          # 3. Set Environment Variables & Allow Executables
          - script: |
              set -e
              # variables from AzDevOps Variable Group
              export SPN_ID=$(SPN_ID)
              export ENVIRONMENT=$(ENVIRONMENT)
              export DATABRICKS_HOST=$(DATABRICKS_HOST)

              # variable dependent from the previous step
              export BUILD_VERSION=$(setTag.BUILD_VERSION)
              export SOURCE_PATH=packages/cdp_core-$(BUILD_VERSION)-py3-none-any.whl
              export TARGET_PATH=/Workspace/Shared/artifacts/cdp_core-$(BUILD_VERSION)-py3-none-any.whl
              export BUNDLE_VAR="environment=$(ENVIRONMENT),whl_path=/Workspace/Shared/artifacts/cdp_core-$(BUILD_VERSION)-py3-none-any.whl,SPN_ID=$(SPN_ID)"

              # Allow the bump-version script to be executable
              chmod +x ./templates/scripts/bump-version.sh
            displayName: "Setting Environment Variables & Allowing Executables"

          # 4. Run PyLint
          - script: |
              pylint src/ --rcfile=.pylintrc --exit-zero
            displayName: "Run PyLint"
          
          # 5. Run YamlLint
          - script: |
              yamllint -c .yamllint . || true
            displayName: "Run YamlLint"

          # 6. Validate Databricks Bundle
          - template: steps/dev_azure_cli.yml
            parameters:
              description: "Validating Databricks Bundle"
              inlineScript: |
                databricks bundle validate --var=$(BUNDLE_VAR)

          # 7. Deploy Databricks Bundle
          - template: steps/dev_azure_cli.yml
            parameters:
              description: "Deploy Databricks Bundle"
              inlineScript: |
                databricks bundle deploy --var=$(BUNDLE_VAR)
          
          # # 8. Run Unit Tests
          # - template: steps/dev_azure_cli.yml
          #   parameters:
          #     description: "Unit Tests"
          #     inlineScript: |
          #       databricks bundle run jb_pytest --var="environment=$(BUNDLE_VAR)
          
          # 9. Copy whl file to gold volume
          - template: steps/dev_azure_cli.yml
            parameters:
              description: "Copying whl file to Shared Area"
              inlineScript: |
                databricks workspace mkdirs /Shared/artifacts
                databricks workspace import --overwrite --format "AUTO" --file $(SOURCE_PATH) $(TARGET_PATH)
                