jobs:
  - job: ProdDeployment
    displayName: "Production Deployment"
    pool:
      name: "vmss-shared"
    steps:
      # Temporary step until prod is fully implemented
      - script: echo "This is a placeholder step in the PROD stage."
        displayName: "Placeholder Step"
