parameters:
  - name: environment
    type: string

stages:
  - stage: PROD
    displayName: "PROD"
    dependsOn: 
      - ProdApproval
    condition: succeeded('TEST')
    jobs:
      # 1. Validate and Deploy Bundle
      - template: modules/jobs/validate_and_deploy.yml
        parameters:
          servicePrincipal: $(SPN_PROD_NAME)
          environment: ${{ parameters.environment }}
