parameters:
  - name: environment
    type: string

stages:
  - stage: PROD
    displayName: "PROD"
    dependsOn: 
      - TEST
      - ProdApproval
    condition: succeeded('TEST')
    jobs:
      - job: PROD
        # pool: 
        #   name: 'vmss-shared'
        displayName: "Deploy Prod"
        variables:
        - template: variables.yml
          parameters:
            environment: ${{ parameters.environment }}

        steps:
          # 1. Install All Requirements
          - script: |
              echo $(DATABRICKS_HOST)
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
            displayName: "Install Databricks CLI"

          # 2. Set Environment Variables & Allow Executables
          - script: |
              set -e
              export DATABRICKS_HOST=$(DATABRICKS_HOST)
              export ENVIRONMENT=$(ENVIRONMENT)
              export SPN_ID=$(SPN_ID)
              chmod +x ./templates/scripts/bump-version.sh
            displayName: "Setting Environment Variables & Allowing Executables"

          # 3. Get and Increment Tag
          - script: templates/scripts/bump-version.sh
            name: TagIncrement
            displayName: "Get and Increment Tag"

          # 4. Validate Databricks Bundle
          - template: steps/prod_azure_cli.yml
            parameters:
              description: "Validating Databricks Bundle"
              inlineScript: |
                databricks bundle validate --var="environment=$(ENVIRONMENT),whl_path=/Workspace/Shared/artifacts/cdp_core-$(BUILD_VERSION)-py3-none-any.whl,SPN_ID=$(SPN_ID)"

          # 4. Deploy Databricks Bundle
          - template: steps/prod_azure_cli.yml
            parameters:
              description: "Deploy Databricks Bundle"
              inlineScript: |
                databricks bundle deploy --var="environment=$(ENVIRONMENT),whl_path=/Workspace/Shared/artifacts/cdp_core-$(BUILD_VERSION)-py3-none-any.whl,SPN_ID=$(SPN_ID)"

