parameters:
  - name: environment
    type: string

stages:
  - stage: TEST
    displayName: "TEST"
    dependsOn: DEV
    condition: succeeded('DEV')
    jobs:
      # 1. Validate and Deploy Bundle
      - template: modules/jobs/validate_and_deploy.yml
        parameters:
          servicePrincipal: $(SPN_TEST_NAME)
          environment: ${{ parameters.environment }}
      
      # 2. Run Integration Tests
      - template: modules/jobs/system_integration_tests.yml
        parameters:
          servicePrincipal: $(SPN_TEST_NAME)
          environment: ${{ parameters.environment }}
